# Generated by Django 4.1.7 on 2023-04-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetconfirmation',
            name='key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
